# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BREW91g9UF4cpSwmq4w5fknshsXa5ceE
"""

import pandas as pd
import requests
def fetch_data(self):
    response = requests.get("<https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json>")
    # Converts JSON response to a Python dictionary
    data = response.json()
    # Converts dictionary to pandas DataFrame
    df = pd.DataFrame(data)
    # Save DataFrame to CSV
    df.to_csv('instruments.csv', index=False)
def get_info_by_symbol(self, symbol):
    # Load data from CSV
    df = pd.read_csv('instruments.csv')
    # Filter rows
    filtered_df = df[df['symbol'] == symbol]
    if not filtered_df.empty:
        # Return the first row of the filtered DataFrame
        return filtered_df.iloc[0]
    # Return None if no matching symbol is found
    return None

print(df)

print(filtered_df)

import pandas as pd
df=pd.read_json("https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json")
print(df)